### ISSUE TITLE
UWA 10.0

### ISSUE THREAD

**Issue by roidy** [Verbon/WinRTMultiBinding#4]
Any chance this could be update to support Windows 10 UWA.

Thanks for a great package :)

**Comment by Verbon** [comment]
@roidy Done! :) Please, download latest WinRT Multibinding package, which now supports Windows 10 UWP apps - https://www.nuget.org/packages/WinRTMultibinding/.

**Comment by roidy** [comment]
Thanks for the very quick update and response, however I cant get the package to install, I get the following errors:- http://pastebin.com/69XGFPxB

Many Thanks

**Comment by Verbon** [comment]
@roidy I'm sorry for the experienced issues, some things went wrong when I built the package. Here's new working version - https://www.nuget.org/packages/WinRTMultibinding.Universal/1.0.0 :) Let me know, if something goes wrong again.

**Comment by roidy** [comment]
Thanks again for another fast update, the package installs fine now however I can't add the namespace:

`xmlns:m="using:WinRTMultibinding"`

Results in an error:- The 'using' URI refers to a namespace 'WinRTMultibinding' that could not be found.

Thanks

**Comment by Verbon** [comment]
Does Visual Studio hightlights this as error or this error appears in the Error List after your build attempt?
If it's the first case - just ignore this and try build and run your app. Sometimes, Visual Studio error highlighter or ReSharper might be mistaken.
If it's the second one - try clean and rebuild.

**Comment by roidy** [comment]
Ok, so I went back to basics and created a new project, added the WinRTMultibinding.Universal package and then pasted the code from your ReadMe into the xaml page and even after cleaning and rebuilding these are the errors I get:-

![capture](https://cloud.githubusercontent.com/assets/4118048/18230818/d00ddddc-729e-11e6-856a-91c2c4e52f7a.PNG)

**Comment by Verbon** [comment]
1) The exact XAML namespace is the following: `xmlns:m="using:WinRTMultibinding.Foundation.Data"`. Sorry, forgot to update examples. This will eliminate `m:Binding` highlighting.
2) After step 1 you still will be unable to build. Please do not copy and paste source code from README, because its only purpose is to show the overall idea of using this package. Build fails because you actually don't have any of types `MyMultiValueConverter`, `MyConverter`, `SomeDataProvider`. To make this work, you should create your own converters, data providers etc. and use them from XAML.

**Comment by roidy** [comment]
> 1) The exact XAML namespace is the following: xmlns:m="using:WinRTMultibinding.Foundation.Data". Sorry, forgot to update examples. This will eliminate m:Binding highlighting.

That works great, Thanks.

> 2) After step 1 you still will be unable to build. Please do not copy and paste source code from README, because its only purpose is to show the overall idea of using this package. Build fails because you actually don't have any of types MyMultiValueConverter, MyConverter, SomeDataProvider. To make this work, you should create your own converters, data providers etc. and use them from XAML.

Yep, I knew the Converters would be missing, it was just the namespace errors I was stuck with. Again a big thanks, great work on a really useful package :)

**Comment by Verbon** [comment]
You're welcome! :)
